using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class UnityLayersGenerator
{
    // Абсолютный путь (для File I/O)
    private static string OutputPath
        => Path.Combine(Application.dataPath, "_Project/Develop/Runtime/Utilities/Generated/UnityLayers.cs");

    // Относительный путь от корня проекта (для AssetDatabase и логов)
    private static string RelativeOutputPath
        => "Assets/_Project/Develop/Runtime/Utilities/Generated/UnityLayers.cs";

    private const string FallbackNamespace = "";

    private static readonly string[] ExcludedLayers = new string[]
    {
        // "Default",
    };

    [InitializeOnLoadMethod]
    [MenuItem("Tools/GenerateUnityLayers")]
    private static void Generate()
    {
        string[] layers = GetAllLayerNames();

        if (layers == null || layers.Length == 0)
        {
            Debug.LogWarning("[UnityLayersGenerator] Не найдено ни одного слоя для генерации.");
            return;
        }

        string targetNamespace = ResolveNamespace();

        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Этот код сгенерирован автоматически. Не редактируйте его вручную.");
        sb.AppendLine("// Инструмент: Tools -> Generate Unity Layers");
        sb.AppendLine($"// Дата генерации: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(targetNamespace);

        if (hasNamespace)
        {
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";

        sb.AppendLine($"{indent}public static class UnityLayers");
        sb.AppendLine($"{indent}{{");

        sb.AppendLine($"{indent}    // Layer IDs");
        foreach (var layer in layers)
        {
            if (string.IsNullOrWhiteSpace(layer)) continue;
            if (IsExcluded(layer)) continue;

            string safeName = SanitizeName(layer);
            sb.AppendLine($"{indent}    public static readonly int Layer{safeName} = LayerMask.NameToLayer(\"{layer}\");");
        }

        sb.AppendLine();

        sb.AppendLine($"{indent}    // Layer Masks");
        foreach (var layer in layers)
        {
            if (string.IsNullOrWhiteSpace(layer)) continue;
            if (IsExcluded(layer)) continue;

            string safeName = SanitizeName(layer);
            sb.AppendLine($"{indent}    public static readonly int LayerMask{safeName} = 1 << Layer{safeName};");
        }

        sb.AppendLine($"{indent}}}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        string newContent = sb.ToString();

        // Проверяем через относительный путь — File.Exists работает с абсолютным,
        // но для консистентности используем OutputPath
        if (File.Exists(OutputPath))
        {
            string oldContent = File.ReadAllText(OutputPath);
            if (RemoveDateLine(oldContent) == RemoveDateLine(newContent))
            {
                Debug.Log("[UnityLayersGenerator] Слои не изменились. Генерация пропущена.");
                return;
            }
        }

        // Создаём директорию по абсолютному пути
        string directory = Path.GetDirectoryName(OutputPath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        // Пишем по абсолютному пути
        File.WriteAllText(OutputPath, newContent);

        // Обновляем AssetDatabase по относительному пути
        AssetDatabase.ImportAsset(RelativeOutputPath, ImportAssetOptions.ForceUpdate);
        AssetDatabase.Refresh();

        Debug.Log($"[UnityLayersGenerator] Сгенерирован файл: {RelativeOutputPath} | Namespace: '{(hasNamespace ? targetNamespace : "<global>")}' | Слоев: {layers.Length}");
    }

    /// <summary>
    /// Определяет namespace через рефлексию.
    /// Сначала пытается найти уже существующий класс UnityLayers во всех сборках,
    /// затем — namespace класса-генератора, иначе — fallback.
    /// </summary>
    private static string ResolveNamespace()
    {
        Type existingType = FindTypeByName("UnityLayers");
        if (existingType != null)
        {
            string ns = existingType.Namespace;
            if (!string.IsNullOrEmpty(ns))
            {
                Debug.Log($"[UnityLayersGenerator] Namespace найден через рефлексию: '{ns}'");
                return ns;
            }
        }

        string generatorNamespace = typeof(UnityLayersGenerator).Namespace;
        if (!string.IsNullOrEmpty(generatorNamespace))
        {
            Debug.Log($"[UnityLayersGenerator] Namespace взят из класса-генератора: '{generatorNamespace}'");
            return generatorNamespace;
        }

        Debug.Log($"[UnityLayersGenerator] Namespace не найден, используется fallback: '{FallbackNamespace}'");
        return FallbackNamespace;
    }

    /// <summary>
    /// Ищет тип по имени среди всех загруженных сборок (рефлексия).
    /// </summary>
    private static Type FindTypeByName(string typeName)
    {
        var localType = Type.GetType(typeName);
        if (localType != null) return localType;

        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            try
            {
                var type = assembly.GetType(typeName, throwOnError: false);
                if (type != null) return type;

                type = assembly.GetTypes().FirstOrDefault(t => t.Name == typeName);
                if (type != null) return type;
            }
            catch (ReflectionTypeLoadException)
            {
                continue;
            }
            catch (Exception)
            {
                continue;
            }
        }

        return null;
    }

    private static string[] GetAllLayerNames()
    {
        try
        {
            var tagManagerAssets = AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset");

            if (tagManagerAssets == null || tagManagerAssets.Length == 0)
            {
                Debug.LogError("[UnityLayersGenerator] Не удалось загрузить TagManager.asset.");
                return null;
            }

            var tagManager = new SerializedObject(tagManagerAssets[0]);
            var layersProperty = tagManager.FindProperty("layers");

            if (layersProperty == null)
            {
                Debug.LogError("[UnityLayersGenerator] Свойство 'layers' не найдено в TagManager.");
                return null;
            }

            var result = new List<string>();

            for (int i = 0; i < layersProperty.arraySize; i++)
            {
                string layerName = layersProperty.GetArrayElementAtIndex(i).stringValue;
                if (string.IsNullOrWhiteSpace(layerName)) continue;
                result.Add(layerName);
            }

            return result.ToArray();
        }
        catch (Exception e)
        {
            Debug.LogError($"[UnityLayersGenerator] Ошибка при чтении слоев: {e.Message}");
            return null;
        }
    }

    private static bool IsExcluded(string layerName)
    {
        foreach (var excluded in ExcludedLayers)
        {
            if (excluded == layerName) return true;
        }
        return false;
    }

    private static string SanitizeName(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Unnamed";

        StringBuilder sb = new StringBuilder();

        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
        }

        string result = sb.ToString();

        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result = "Layer" + result;
        }

        return string.IsNullOrEmpty(result) ? "Unnamed" : result;
    }

    private static string RemoveDateLine(string content)
    {
        var lines = content.Split('\n');
        var sb = new StringBuilder();

        foreach (var line in lines)
        {
            if (line.Contains("// Дата генерации:")) continue;
            sb.AppendLine(line);
        }

        return sb.ToString();
    }
}